"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

import version

APP = ['spacehaven-modloader.py']
DATA_FILES = []
OPTIONS = {}

setup(
    name="spacehaven-modloader",
    version=version.version,
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app==0.19'],
    install_requires=[
        'lxml',
        'click',
        'pypng'
    ]
)
